openapi: 3.0.0
info:
  title: Mi API
  description: Esta es una API.
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/
paths:
  /products:
    get:
      summary: Obtener lista de usuarios
      description: Retorna una lista de productos del sistema.
      responses:
        "200":
          description: Una lista de usuarios.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Usuario"
  /products/{id}:
    get:
      summary: Obtener un usuario por ID
      description: Retorna un único usuario basado en su ID.
      parameters:
        - name: id
          in: path
          required: true
          description: ID del usuario que se desea obtener
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Detalles del usuario.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Usuario"
        "404":
          description: Usuario no encontrado
components:
  schemas:
    Usuario:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nombre:
          type: string
        email:
          type: string
          format: email
      required:
        - id
        - nombre
        - email
